// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJqGzlw4I_LcfzZtzb5P9vSynqzzBKS18',
    appId: '1:39884725639:web:34707a27792759736b0722',
    messagingSenderId: '39884725639',
    projectId: 'streaming-api-8313d',
    authDomain: 'streaming-api-8313d.firebaseapp.com',
    storageBucket: 'streaming-api-8313d.appspot.com',
    measurementId: 'G-841DNRF6L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdc0wZEU_8LcwE4S-K1VAMY_Mtsm9Qjg',
    appId: '1:39884725639:android:de67245f456c4bb26b0722',
    messagingSenderId: '39884725639',
    projectId: 'streaming-api-8313d',
    storageBucket: 'streaming-api-8313d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrxrGxki_gDidVhSMUeLqolDvnjFJ78UM',
    appId: '1:39884725639:ios:75dd70688d77095f6b0722',
    messagingSenderId: '39884725639',
    projectId: 'streaming-api-8313d',
    storageBucket: 'streaming-api-8313d.appspot.com',
    iosBundleId: 'com.example.streamingFrontApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrxrGxki_gDidVhSMUeLqolDvnjFJ78UM',
    appId: '1:39884725639:ios:2e28853a904eba6d6b0722',
    messagingSenderId: '39884725639',
    projectId: 'streaming-api-8313d',
    storageBucket: 'streaming-api-8313d.appspot.com',
    iosBundleId: 'com.example.streamingFrontApp.RunnerTests',
  );
}
